version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - website

  webapplication:
    build: /root/firstcompose
    depends_on:
      - dbservice
    ports:
      - "80:80"
    networks:
      - website
networks:
  website:

